const formSchema = [
  {
    id: "customer_name",
    label: "Customer Name*",
    type: "text",
    defaultValue: "",
    required: true,
  },
  {
    id: "customer_type",
    label: "Customer Type*",
    type: "select",
    defaultValue: "New",
    options: ["New", "Existing"],
    required: true,
  },
  {
    id: "business_type",
    label: "Business Type*",
    type: "select",
    defaultValue: "Government",
    options: ["Government", "Private"],
    required: true,
  },
  {
    id: "guarantee",
    label: "Guarantee Needed*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "opportunity",
    label: "Opportunity*",
    type: "select",
    defaultValue: "New",
    options: ["New", "Renewal"],
    required: true,
  },
  {
    id: "bidding",
    label: "RFP/RFI/RFQ/Bidding*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "start_date",
    label: "Project Start Date*",
    type: "date",
    defaultValue: "",
    required: true,
  },
  {
    id: "end_date",
    label: "Project End Date*",
    type: "date",
    defaultValue: "",
    required: true,
  },
  {
    id: "total_contract",
    label: "Total Contract Period*",
    type: "text",
    defaultValue: "",
    required: true,
  },
  {
    id: "region",
    label: "Region*",
    type: "select",
    defaultValue: "Taiwan",
    options: [
      "Taiwan",
      "Egypt",
      "UK",
      "Columbia",
      "Thailand",
      "Singapore",
      "India",
      "US",
    ],
    required: true,
  },
  {
    id: "domain",
    label: "Domain*",
    type: "select",
    defaultValue: "IoT",
    options: ["IoT", "Security", "Telecom", "Video"],
    required: true,
  },
  {
    id: "direct_sale",
    label: "Direct Sale*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "partner",
    label: "Partner*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "third_party",
    label: "3rd Party*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "penalty",
    label: "Penalty*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "acc_manager",
    label: "Account Manager*",
    type: "text",
    defaultValue: "",
    required: true,
  },
  {
    id: "presales_spoc",
    label: "Pre Sales SPOC*",
    type: "text",
    defaultValue: "",
    required: true,
  },
  {
    id: "currency",
    label: "Pricing Currency*",
    type: "select",
    defaultValue: "EGP",
    options: ["EGP", "NTD", "THB", "USD","GBP","INR"],
    required: true,
  },
  {
    id: "cust_budget",
    label: "Customer Budget",
    type: "integer",
    defaultValue: "0",
  },
  {
    id: "travel_expense",
    label: "Travel Expense",
    type: "integer",
    defaultValue: "0",
  },
  {
    id: "tool_license",
    label: "Tool License*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "shift_allowance",
    label: "Shift Allowance*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "weekend_allowance",
    label: "Weekend Allowance*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "on_call_allowance",
    label: "On Call Allowance*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },
  {
    id: "one_time_cost",
    label: "One Time Cost*",
    type: "select",
    defaultValue: "No",
    options: ["Yes", "No"],
    required: true,
  },

  { 
    id: "vat", 
    label: "VAT*", 
    type: "integer", 
    defaultValue: "5" 
  },

  {
    id: "misc",
    label: "Miscellaneous",
    type: "text",
    defaultValue: "",
  },

  {
    id: "workNature",
    label: "Work Nature*",
    type: "checkbox",
    options: [
      "Software",
      "Hardware",
      "License",
      "Customization",
      "Enhancement",
      "Deployment",
      "Support",
      "Professional Services",
    ],
    required: true,
  },
];

export default formSchema;
